#!/bin/sh


echo "Signing ..."
ldid -s /usr/lib/libCrossOverIPC.dylib /usr/lib/libCrossOverIPC.dylib
ldid -s /usr/lib/libCrossOverIPC.dylib /Library/MobileSubstrate/DynamicLibraries/0000CrossOverIPC.dylib
echo "Done!"
exit 0