#!/bin/sh



echo "Signing ..."
ldid -s /usr/local/libexec/xpcToolStrapd /Library/MobileSubstrate/DynamicLibraries/CrossOverIPC_Apps.dylib
ldid -s /usr/local/libexec/xpcToolStrapd /Library/MobileSubstrate/DynamicLibraries/CrossOverIPC_SB.dylib